
import { Project, ProjectCategory, Service } from './types';

const PROJECTS_RU: Project[] = [
  {
    id: '1',
    code: 'V_100',
    client: 'WILDBERRIES',
    title: 'ГОНКА ЗА СКИДКАМИ',
    category: 'WILDBERRIES',
    year: '2025',
    status: "TV 30'",
    target: 'WILDBERRIES',
    description: 'Высокоскоростной монтаж для федеральной кампании. Акцент на динамике потребления.',
    task: 'Привлечь молодую аудиторию стильным роликом на Back to School',
    idea: 'Каждый учебный год похож на новый круг в гоночном заезде. Чтобы не выбыть из гонки, нужен надёжный пит-стоп.\n\nМаркетплейс в команде с родителями обновляет ребёнка к школе: вместо болида — скейт, вместо шин — рюкзаки и тетради.',
    specs: ['PRODUCTION', 'COLOR', 'SOUND'],
    imageUrl: 'https://picsum.photos/1920/1080?random=1',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%93%D0%BE%D0%BD%D0%BA%D0%B0_%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%92%D0%91%20%E2%80%93%20%D0%B3%D0%BE%D0%BD%D0%BA%D0%B0%20%D0%B7%D0%B0%20%D1%81%D0%BA%D0%B8%D0%B4%D0%BA%D0%B0%D0%BC%D0%B8.mp4',
  },
  {
    id: '2',
    code: 'V_099',
    client: 'БАЛТИКА',
    title: 'ПОСЫЛКА',
    category: 'БАЛТИКА',
    year: '2025',
    status: "TV 70'",
    target: 'БАЛТИКА',
    description: 'Масштабная имиджевая история.',
    task: 'Придумать ролик о добрых и бескорыстных поступках',
    idea: 'Простое решение — не всегда верное. Иногда ты выбираешь долгий путь, потому что так правильно.\n\nГерой получает чужую посылку и отправляется на поиски настоящего адресата.',
    specs: ['ARRI ALEXA', 'STORYTELLING', 'GRADE'],
    imageUrl: 'https://picsum.photos/1920/1080?random=2',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%91%D0%B0%D0%BB%D1%82%D0%B8%D0%BA%D0%B0%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%91%D0%B0%D0%BB%D1%82%D0%B8%D0%BA%D0%B0_-_%D0%9F%D0%BE%D1%81%D1%8B%D0%BB%D0%BA%D0%B0%20(1080p).mp4'
  },
  {
    id: '3',
    code: 'V_098',
    client: 'WILDBERRIES',
    title: 'РАСПРОЖАРА',
    category: 'WILDBERRIES',
    year: '2025',
    status: "TV 20'",
    target: 'WILDBERRIES',
    description: 'Яркая летняя кампания.',
    task: 'Придумать ролик о дачной распродаже и показать новую функцию «Поиск по фото»',
    idea: 'Люди часто хотят, чтобы «как у соседа», но спрашивать — неловко. С новой функцией — достаточно незаметно сфоткать.\n\nРаспрожара — это шпионский триллер о том, как герой проникает на участок к соседу, чтобы снять его газонокосилку и найти такую же на ВБ.',
    specs: ['CGI', 'COMPOSITING', 'BROADCAST'],
    imageUrl: 'https://picsum.photos/1920/1080?random=3',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%A0%D0%B0%D1%81%D0%BF%D1%80%D0%BE%D0%B6%D0%B0%D1%80%D0%B0%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/250417_WB_20s_v03%20(1).mp4'
  },
  {
    id: '4',
    code: 'V_097',
    client: 'WILDBERRIES',
    title: 'ОНО ТОГО СТОИТ',
    category: 'WILDBERRIES',
    year: '2026',
    status: "TV 30'",
    target: 'WILDBERRIES',
    description: 'Новогодняя имиджевая кампания.',
    task: 'Придумать ролик к новогодней распродаже, актуальный сразу для нескольких стран',
    idea: 'Дети спешат повзрослеть, а взрослые ведут себя как дети. Конфликт поколений знаком всем.\n\nДевочка-подросток не видит смысла отмечать Новый год. Но, наблюдая за папой, который радуется как ребёнок, она хочет стать частью праздника. Девочка понимает: «Оно того стоит»',
    specs: ['VFX', 'MOTION CONTROL', 'FUTURE_TECH'],
    imageUrl: 'https://picsum.photos/1920/1080?random=4',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%9E%D0%BD%D0%BE%20%D1%82%D0%BE%D0%B3%D0%BE%20%D1%81%D1%82%D0%BE%D0%B8%D1%82%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/WB_35s_no_legal.mp4'
  },
  {
    id: '5',
    code: 'V_096',
    client: 'ЛЕНТА',
    title: '30 ЛЕТ ВМЕСТЕ',
    category: 'ЛЕНТА',
    year: '2024',
    status: "TV 60'",
    target: 'ЛЕНТА',
    description: 'Юбилейный ролик.',
    task: 'Придумать ролик к 30-летию бренда в креативной рамке о семье Пушкиных',
    idea: 'За 30 лет двое взрослых становятся семьёй. За 30 лет ребёнок становится взрослым. За 30 лет всё меняется: желания, а вместе с ними — и позиции в чеке.\n\nМы показали историю становления семьи. На каждом этапе — Лента рядом. Магазин закрывает новые потребности Пушкиных, чтобы они не отвлекались от главного.',
    specs: ['DIRECTING', 'CASTING', 'CINEMATOGRAPHY'],
    imageUrl: 'https://picsum.photos/1920/1080?random=5',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/lenta%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/lenta.mp4'
  },
  {
    id: '6',
    code: 'V_095',
    client: 'ТРИКОЛОР',
    title: 'БАБУЛЯ-ГИК',
    category: 'ТРИКОЛОР',
    year: '2023',
    status: "OLV 10'",
    target: 'ТРИКОЛОР',
    description: 'Юмористическая серия коротких роликов.',
    task: 'Рассказать о новой возможности смотреть кино и сериалы в онлайн-сервисе',
    idea: 'Обычно современный контент не заходит бабушкам. Но какими будут последствия, если им всё же понравится?\n\nИстория о бабушке, которая открыла для себя мир онлайн контента и теперь шокирует внука своей гиканутостью.',
    specs: ['CHARACTER DESIGN', 'HUMOR', 'SOCIAL'],
    imageUrl: 'https://picsum.photos/1920/1080?random=6',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B1%D0%B0%D0%B1%D1%83%D0%BB%D1%8F%20%D0%B3%D0%B8%D0%BA%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B1%D0%B0%D0%B1%D1%83%D0%BB%D1%8F%20%D0%B3%D0%B8%D0%BA.mp4'
  },
  {
    id: '7',
    code: 'V_094',
    client: 'WILDBERRIES',
    title: 'ПУШИ С ЗАБОТОЙ',
    category: 'WILDBERRIES',
    year: '2024',
    status: 'СПЕЦПРОЕКТ',
    target: 'WILDBERRIES',
    description: 'Социальный спецпроект.',
    task: 'Придумать спецпроект, который изменит отношение к уведомлениям от Wildberries',
    idea: 'Пушам от ВБ не хватало чего-то человечного, а что может быть человечнее, чем забота бабули?\n\nОтправили уведомления про шапочку и шарфик от бабушек из фонда «Люди.Идеи». Спецпроект подкрепили роликом, чтобы привлечь внимание к пожилым людям — удалось собрать около 4 млн рублей.',
    specs: ['DIGITAL', 'UX/UI', 'INTERACTIVE'],
    imageUrl: 'https://picsum.photos/1920/1080?random=7',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%BF%D1%83%D1%88%D0%B8%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/WB-Push_v3_CG-v1C_Subtitles.mp4'
  },
  {
    id: '8',
    code: 'V_093',
    client: 'WILDBERRIES',
    title: 'ЛЮДИ ВЫБИРАЮТ ВЭБЭШЕЧКУ',
    category: 'WILDBERRIES',
    year: '2025',
    status: 'СПЕЦПРОЕКТ',
    target: 'WILDBERRIES',
    description: 'Вирусная наружная реклама.',
    task: 'Подкрепить «народность» бренда через имиджевый спецпроект в наружке',
    idea: 'Название бренда длинное — люди коверкают его, как хотят. Мы переделали брендлайн с учётом «народных» названий WB. Сначала запустили билборд с малозаметной ошибкой в названии — соцсети наплодили посты на тему: «Кого-то скоро уволят». Затем мы вывели в наружку все возможные вариации названия WB.',
    specs: ['VIRAL', 'SOCIAL MEDIA', 'BRANDING'],
    imageUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B2%D1%8D%D0%B1%D1%8D%D1%88%D0%B5%D1%87%D0%BA%D0%B0.png',
    extraVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%98%D0%9D%D0%A2%D0%95%D0%A0%D0%92%D0%AC%D0%AE.mp4',
    extraVideoText: 'Финалом стало короткое видео для посевов в Telegram — закрывающий контент, который расставлял точки и объяснял идею проекта всем, кто следил за этой историей.'
  },
  {
    id: '9',
    code: 'V_092',
    client: 'М.ВИДЕО',
    title: 'ЗАЧЁТНАЯ РАСПРОДАЖА',
    category: 'М.ВИДЕО',
    year: '2025',
    status: "OLV 10'",
    target: 'М.ВИДЕО',
    description: 'Back to School кампания.',
    task: 'Создать OLV-кампанию для сезона Back to School',
    idea: 'Зачётная Распродажа — онлайн уроки с селебом-репетитором о том, как выгодно закупиться к школе. Проводятся на Miro-доске, содержат приколы.',
    specs: ['EDITING', 'MOTION GRAPHICS', 'SOUND FX'],
    imageUrl: 'https://picsum.photos/1920/1080?random=9',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%9C%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%97%D0%B0%D1%87%D0%B5%D1%82%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B6%D0%B0%20%E2%80%94%C2%A0%D0%9D%D0%B0%20%D0%BD%D0%BE%D0%BB%D1%8C%20%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D1%8C%20%D0%BD%D0%B5%D0%BB%D1%8C%D0%B7%D1%8F.mp4'
  },
  {
    id: '10',
    code: 'V_091',
    client: 'ОКСКОЕ',
    title: 'СВЕЖИЙ ПОВОД',
    category: 'ОКСКОЕ',
    year: '2023',
    status: 'OOH',
    target: 'ОКСКОЕ',
    description: 'Локальная кампания для Нижнего Новгорода.',
    task: 'Рассказать жителям Нижнего Новгорода про обновлённое Окское Мягкое',
    idea: 'Локальность бренда дала возможность объединить людей вокруг Нижнего Новгорода.\n\nСвежий повод пересечься всем друзьям Нижнего. Кампания в дружеском тоне, чтобы наполнить лайны душевностью, а стаканы — Окским.',
    specs: ['PRINT', '3D RENDER', 'OUTDOOR'],
    imageUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-02-06%20%D0%B2%2000.03.53.png'
  },
  {
    id: '11',
    code: 'V_090',
    client: 'B52',
    title: 'НЕЙРОВИДЕО',
    category: 'AI VIDEO',
    year: '2025–2026',
    status: 'AI VIDEO',
    target: 'B52',
    description: 'Серия AI-видео проекта B52.',
    task: '',
    idea: '',
    specs: ['AI', 'SUNO', 'MIDJOURNEY', 'KLING', 'RUNWAY'],
    imageUrl: 'https://picsum.photos/1920/1080?random=11',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B8%D0%B8%20%D0%B2%D0%B8%D0%B4%D0%BE%D1%81%D1%8B/neuralpreview.mp4',
  },
  {
    id: '12',
    code: 'V_089',
    client: 'EVENT PRODUCTION',
    title: 'ИВЕНТЫ',
    category: 'ИВЕНТЫ',
    year: '2024–2025',
    status: 'EVENT',
    target: 'EVENT',
    description: 'Концепции и продакшн мероприятий для крупных брендов.',
    task: '',
    idea: '',
    specs: ['EVENT', 'CONCEPT', 'PRODUCTION', 'ACTIVATION'],
    imageUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B8%D0%B2%D0%B5%D0%BD%D1%82%D1%8B/upload-30029aaf-d46c-4970-9435-eff16c647480.gif',
  },
];

const PROJECTS_EN: Project[] = [
  {
    id: '1',
    code: 'V_100',
    client: 'WILDBERRIES',
    title: 'DISCOUNT RACE',
    category: 'WILDBERRIES',
    year: '2025',
    status: "TV 30'",
    target: 'WILDBERRIES',
    description: 'High-speed editing for a federal campaign. Focus on consumption dynamics.',
    task: 'Attract a young audience with a stylish Back to School video',
    idea: 'Every school year feels like a new lap in a race. To stay in the game, you need a reliable pit stop.\n\nThe marketplace teams up with parents to gear up the kid for school: instead of a racing car — a skateboard, instead of tires — backpacks and notebooks.',
    specs: ['PRODUCTION', 'COLOR', 'SOUND'],
    imageUrl: 'https://picsum.photos/1920/1080?random=1',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%93%D0%BE%D0%BD%D0%BA%D0%B0_%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%92%D0%91%20%E2%80%93%20%D0%B3%D0%BE%D0%BD%D0%BA%D0%B0%20%D0%B7%D0%B0%20%D1%81%D0%BA%D0%B8%D0%B4%D0%BA%D0%B0%D0%BC%D0%B8.mp4',
  },
  {
    id: '2',
    code: 'V_099',
    client: 'BALTIKA',
    title: 'THE PARCEL',
    category: 'BALTIKA',
    year: '2025',
    status: "TV 70'",
    target: 'BALTIKA',
    description: 'Large-scale brand image story.',
    task: 'Create a video about kind and selfless acts',
    idea: 'The easy choice isn\'t always the right one. Sometimes you take the long road because it\'s the right thing to do.\n\nThe hero receives someone else\'s parcel and sets off to find the real recipient.',
    specs: ['ARRI ALEXA', 'STORYTELLING', 'GRADE'],
    imageUrl: 'https://picsum.photos/1920/1080?random=2',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%91%D0%B0%D0%BB%D1%82%D0%B8%D0%BA%D0%B0%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%91%D0%B0%D0%BB%D1%82%D0%B8%D0%BA%D0%B0_-_%D0%9F%D0%BE%D1%81%D1%8B%D0%BB%D0%BA%D0%B0%20(1080p).mp4'
  },
  {
    id: '3',
    code: 'V_098',
    client: 'WILDBERRIES',
    title: 'SALE INFERNO',
    category: 'WILDBERRIES',
    year: '2025',
    status: "TV 20'",
    target: 'WILDBERRIES',
    description: 'Bright summer campaign.',
    task: 'Create a video about a summer sale and showcase the new "Search by Photo" feature',
    idea: 'People often want "the same thing as the neighbor\'s" but asking feels awkward. With the new feature — just snap a photo discreetly.\n\nSale Inferno is a spy thriller about a hero sneaking into the neighbor\'s yard to photograph his lawnmower and find the same one on WB.',
    specs: ['CGI', 'COMPOSITING', 'BROADCAST'],
    imageUrl: 'https://picsum.photos/1920/1080?random=3',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%A0%D0%B0%D1%81%D0%BF%D1%80%D0%BE%D0%B6%D0%B0%D1%80%D0%B0%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/250417_WB_20s_v03%20(1).mp4'
  },
  {
    id: '4',
    code: 'V_097',
    client: 'WILDBERRIES',
    title: 'WORTH IT',
    category: 'WILDBERRIES',
    year: '2026',
    status: "TV 30'",
    target: 'WILDBERRIES',
    description: 'New Year brand image campaign.',
    task: 'Create a New Year sale video relevant across multiple countries',
    idea: 'Kids rush to grow up, while adults act like children. The generational conflict is universal.\n\nA teenage girl sees no point in celebrating New Year. But watching her dad light up like a kid, she wants to be part of the holiday. She realizes: "It\'s worth it."',
    specs: ['VFX', 'MOTION CONTROL', 'FUTURE_TECH'],
    imageUrl: 'https://picsum.photos/1920/1080?random=4',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%9E%D0%BD%D0%BE%20%D1%82%D0%BE%D0%B3%D0%BE%20%D1%81%D1%82%D0%BE%D0%B8%D1%82%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/WB_35s_no_legal.mp4'
  },
  {
    id: '5',
    code: 'V_096',
    client: 'LENTA',
    title: '30 YEARS TOGETHER',
    category: 'LENTA',
    year: '2024',
    status: "TV 60'",
    target: 'LENTA',
    description: 'Anniversary video.',
    task: 'Create an anniversary video for the brand\'s 30th birthday within a creative framework about the Pushkin family',
    idea: 'In 30 years, two adults become a family. In 30 years, a child becomes an adult. In 30 years, everything changes: desires, and with them — the items on the receipt.\n\nWe showed the story of a family growing up. At every stage — Lenta is there. The store covers the Pushkins\' new needs so they can focus on what matters most.',
    specs: ['DIRECTING', 'CASTING', 'CINEMATOGRAPHY'],
    imageUrl: 'https://picsum.photos/1920/1080?random=5',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/lenta%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/lenta.mp4'
  },
  {
    id: '6',
    code: 'V_095',
    client: 'TRICOLOR',
    title: 'GRANDMA GEEK',
    category: 'TRICOLOR',
    year: '2023',
    status: "OLV 10'",
    target: 'TRICOLOR',
    description: 'Humorous short video series.',
    task: 'Introduce the new ability to watch movies and series on the streaming service',
    idea: 'Modern content usually doesn\'t appeal to grandmas. But what would happen if they actually liked it?\n\nThe story of a grandma who discovered the world of online content and now shocks her grandson with her geekiness.',
    specs: ['CHARACTER DESIGN', 'HUMOR', 'SOCIAL'],
    imageUrl: 'https://picsum.photos/1920/1080?random=6',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B1%D0%B0%D0%B1%D1%83%D0%BB%D1%8F%20%D0%B3%D0%B8%D0%BA%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B1%D0%B0%D0%B1%D1%83%D0%BB%D1%8F%20%D0%B3%D0%B8%D0%BA.mp4'
  },
  {
    id: '7',
    code: 'V_094',
    client: 'WILDBERRIES',
    title: 'PUSH WITH CARE',
    category: 'WILDBERRIES',
    year: '2024',
    status: 'SPECIAL PROJECT',
    target: 'WILDBERRIES',
    description: 'Social special project.',
    task: 'Create a special project that changes attitudes toward Wildberries push notifications',
    idea: 'WB push notifications lacked a human touch, and what could be more human than a grandma\'s care?\n\nWe sent notifications about hats and scarves from grandmothers at the "People.Ideas" foundation. The special project was supported by a video to draw attention to elderly people — raising about 4 million rubles.',
    specs: ['DIGITAL', 'UX/UI', 'INTERACTIVE'],
    imageUrl: 'https://picsum.photos/1920/1080?random=7',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%BF%D1%83%D1%88%D0%B8%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/WB-Push_v3_CG-v1C_Subtitles.mp4'
  },
  {
    id: '8',
    code: 'V_093',
    client: 'WILDBERRIES',
    title: 'PEOPLE CHOOSE WB',
    category: 'WILDBERRIES',
    year: '2025',
    status: 'SPECIAL PROJECT',
    target: 'WILDBERRIES',
    description: 'Viral outdoor advertising.',
    task: 'Reinforce the brand\'s "people\'s" identity through a brand image outdoor special project',
    idea: 'The brand name is long — people mangle it however they like. We redesigned the brand line with "folk" WB name variations. First, we launched a billboard with a subtle typo in the name — social media exploded with posts: "Someone\'s getting fired." Then we rolled out every possible WB name variation on outdoor ads.',
    specs: ['VIRAL', 'SOCIAL MEDIA', 'BRANDING'],
    imageUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B2%D1%8D%D0%B1%D1%8D%D1%88%D0%B5%D1%87%D0%BA%D0%B0.png',
    extraVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%98%D0%9D%D0%A2%D0%95%D0%A0%D0%92%D0%AC%D0%AE.mp4',
    extraVideoText: 'The finale was a short video for Telegram seeding — closing content that connected the dots and explained the project\'s idea to everyone following the story.'
  },
  {
    id: '9',
    code: 'V_092',
    client: 'M.VIDEO',
    title: 'A+ SALE',
    category: 'M.VIDEO',
    year: '2025',
    status: "OLV 10'",
    target: 'M.VIDEO',
    description: 'Back to School campaign.',
    task: 'Create an OLV campaign for the Back to School season',
    idea: 'A+ Sale — online lessons with a celebrity tutor on how to shop smart for school. Hosted on a Miro board, packed with jokes.',
    specs: ['EDITING', 'MOTION GRAPHICS', 'SOUND FX'],
    imageUrl: 'https://picsum.photos/1920/1080?random=9',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%9C%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%B0%D1%8F.mp4',
    fullVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%97%D0%B0%D1%87%D0%B5%D1%82%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B6%D0%B0%20%E2%80%94%C2%A0%D0%9D%D0%B0%20%D0%BD%D0%BE%D0%BB%D1%8C%20%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D1%8C%20%D0%BD%D0%B5%D0%BB%D1%8C%D0%B7%D1%8F.mp4'
  },
  {
    id: '10',
    code: 'V_091',
    client: 'OKSKOYE',
    title: 'FRESH REASON',
    category: 'OKSKOYE',
    year: '2023',
    status: 'OOH',
    target: 'OKSKOYE',
    description: 'Local campaign for Nizhny Novgorod.',
    task: 'Tell the residents of Nizhny Novgorod about the updated Okskoye Soft',
    idea: 'The brand\'s local roots opened the door to unite people around Nizhny Novgorod.\n\nA fresh reason for all friends in Nizhny to get together. A campaign in a friendly tone, to fill the lines with warmth and the glasses with Okskoye.',
    specs: ['PRINT', '3D RENDER', 'OUTDOOR'],
    imageUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-02-06%20%D0%B2%2000.03.53.png'
  },
  {
    id: '11',
    code: 'V_090',
    client: 'B52',
    title: 'NEURAL VIDEO',
    category: 'AI VIDEO',
    year: '2025–2026',
    status: 'AI VIDEO',
    target: 'B52',
    description: 'AI video series by project B52.',
    task: '',
    idea: '',
    specs: ['AI', 'SUNO', 'MIDJOURNEY', 'KLING', 'RUNWAY'],
    imageUrl: 'https://picsum.photos/1920/1080?random=11',
    previewVideoUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B8%D0%B8%20%D0%B2%D0%B8%D0%B4%D0%BE%D1%81%D1%8B/neuralpreview.mp4',
  },
  {
    id: '12',
    code: 'V_089',
    client: 'EVENT PRODUCTION',
    title: 'EVENTS',
    category: 'EVENTS',
    year: '2024–2025',
    status: 'EVENT',
    target: 'EVENT',
    description: 'Event concepts and production for major brands.',
    task: '',
    idea: '',
    specs: ['EVENT', 'CONCEPT', 'PRODUCTION', 'ACTIVATION'],
    imageUrl: 'https://storage.yandexcloud.net/vodichkacrew/%D0%B8%D0%B2%D0%B5%D0%BD%D1%82%D1%8B/upload-30029aaf-d46c-4970-9435-eff16c647480.gif',
  },
];

const UI_RU = {
  cursor_target: 'ЦЕЛЬ_ЗАХВАЧЕНА',
  nav_online: 'В СЕТИ',
  monitor_pressure: 'PRESSURE',
  monitor_flow: 'FLOW',
  monitor_purity: 'PURITY',
  monitor_temp: 'TEMP',
  hero_manifesto: 'Привет, это Водичка Крю – Команда креативщиков. Мы придумываем идеи, ролики, спецпроекты, активации и пьём водичку',
  project_list_title: 'Portfolio_projects', // Updated from DATABASE_LOADED
  project_count: 'ENTITIES',
  project_target_preview: 'TARGET_SCAN',
  project_year: 'ГОД',
  project_status: 'СТАТУС',
  about_tag: 'кто_такие_водичка_крю', // Updated tag
  about_title: 'МЫ ПРОЗРАЧНЫЕ',
  about_text_1: 'ПРОЗРАЧНАЯ РАБОТА: В наших креативах продукт имеет чёткую роль. Мы решаем задачи из брифа, а не закрываем творческие гештальты.<br/><br/>ПРОЗРАЧНЫЕ ИДЕИ: Нам на троих — сотня с лишним лет. Мы много чего повидали и теперь пользуемся этим в работе. Наши идеи строятся на понятных человеческих инсайтах, поэтому их запоминают.',
  about_text_2: 'ПРОЗРАЧНЫЕ НАМЕРЕНИЯ: Мы занимаемся рекламой, чтобы зарабатывать. Лучший способ зарабатывать больше — это работать быстро и качественно. Так мы и делаем.',
  detail_review: 'PORTFOLIO', // Updated
  detail_close: 'ЗАКРЫТЬ [ESC]',
  detail_render: 'TV РОЛИК', // Updated
  detail_client: 'КЛИЕНТ',
  detail_year: 'ГОД',
  detail_specs: 'СПЕКИ',
  detail_task: 'ЗАДАЧА', // New
  detail_idea: 'ИДЕЯ', // New
  detail_playback: 'ВОСПРОИЗВЕДЕНИЕ: RAW',
  footer_slogan: 'ВСЕМ НУЖНА ВОДИЧКА'
};

const UI_EN = {
  cursor_target: 'TARGET_LOCKED',
  nav_online: 'ONLINE',
  monitor_pressure: 'PRESSURE',
  monitor_flow: 'FLOW',
  monitor_purity: 'PURITY',
  monitor_temp: 'TEMP',
  hero_manifesto: 'Hi, this is Vodichka Crew – A team of creatives. We invent ideas, videos, special projects, activations and drink water.',
  project_list_title: 'PORTFOLIO_PROJECTS', // Updated
  project_count: 'ENTITIES',
  project_target_preview: 'TARGET_SCAN',
  project_year: 'YEAR',
  project_status: 'STATUS',
  about_tag: 'WHO_IS_VODICHKA_CREW',
  about_title: 'WE ARE TRANSPARENT',
  about_text_1: 'TRANSPARENT WORK: In our creatives, the product has a clear role. We solve brief tasks, not close creative gestalts.<br/><br/>TRANSPARENT IDEAS: Between the three of us, we have over a hundred years. We use this experience. Our ideas are built on clear human insights.',
  about_text_2: 'TRANSPARENT INTENTIONS: We are in advertising to make money. The best way to earn more is to work quickly and with quality. That is what we do.',
  detail_review: 'PORTFOLIO', // Updated
  detail_close: 'CLOSE [ESC]',
  detail_render: 'TV SPOT', // Updated
  detail_client: 'CLIENT',
  detail_year: 'YEAR',
  detail_specs: 'SPECS',
  detail_task: 'TASK', // New
  detail_idea: 'IDEA', // New
  detail_playback: 'PLAYBACK: RAW',
  footer_slogan: 'EVERYONE NEEDS WATER'
};

export const CONTENT = {
  RU: {
    PROJECTS: PROJECTS_RU,
    UI: UI_RU
  },
  EN: {
    PROJECTS: PROJECTS_EN,
    UI: UI_EN
  }
};